version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - database
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - APP_PORT
      - APP_NAME
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    expose:
      - 3000
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  database:
    image: mongo
    container_name: "mongodb"
    env_file:
      - .env
    volumes:
      - ./home/mongodb:/home/mongodb
      - ./mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_DB_ROOT_USERNAME
      - MONGO_DB_ROOT_PASSWORD
      - MONGO_DB_DATABASE
    networks:
      - app-network
    expose:
      - 27017
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: