# Service
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: database
---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo
  name: mongodb
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        selector: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
          ports:
            - containerPort: 27017
              name: web
          volumeMounts:
            - name: database
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_DATABASE
              value: subscribe
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: rootpassword
  volumeClaimTemplates:
    - metadata:
        name: database
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
#      nodeSelector:
#        kubernetes.io/hostname: mongodb

# Storage
#---
#apiVersion: storage.k8s.io/v1beta1
#kind: StorageClass
#metadata:
#  name: fast
#provisioner: kubernetes.io/gce-pd
#parameters:
#  type: pd-ssd
#
#---
# Secret
#apiVersion: v1
#kind: Secret
#metadata:
#  name: mongod-keyfile
#type: Opaque
#data:
#  mongod.keyfile: eyJNT05HT19JTklUREJfUk9PVF9VU0VSTkFNRSI6InJvb3QiLCJNT05HT19JTklUREJfUk9PVF9QQVNTV09SRCI6InJvb3RwYXNzd29yZCJ9
#---